### ISSUE TITLE
Dockerfile incomplete since 38188d2

### ISSUE THREAD

**Issue by fwaggle** [alfg/murmur-rest#13]
I'm not a docker user so I'm not 100% sure on this, but I think when I made 38188d2a0fdcc5822ffe4f519e0425cbb38dcf1d I might have inadvertently broken the included docker container - it probably needs something in there to copy settings.py.example to settings.py.

If I get around to it I'll test this later.

**Comment by alfg** [comment]
Good catch! Just added a fix. :)
