### ISSUE TITLE
Update Root Channel

### ISSUE THREAD

**Issue by Elithrin** [alfg/murmur-rest#19]
Hello,

How i can edit the name of the root channel ?

There is no function for set the name of channel ID = 0

Thanks

**Comment by alfg** [comment]
Hi @Elithrin, 

Are you referring to the register name? I think the root channel uses the register name. If so, you can configure it from the POST `/servers/:id/conf` endpoint.

Example:
`curl -u "user:pass" -X POST -F "key=registername" -F "value=test channel name" http://127.0.0.1:5000/server/1/conf -v --digest -c ./cookie`

You can set any server config key from this endpoint.

**Comment by Elithrin** [comment]
Thanks ! It's working !
