### ISSUE TITLE
Rename User

### ISSUE THREAD

**Issue by zachlevy** [alfg/murmur-rest#26]
Is it possible to rename a User? similar to the functionality below

https://www.mumble.com/support/mumble-changing-registered-user.php

**Comment by alfg** [comment]
Hi @zachlevy, 

It seems this is possible via the Ice API: http://mumble.sourceforge.net/slice/1.2.7/Murmur/Server.html#updateRegistration

However the functionality is not built into this project yet. I'll look into experimenting with this feature in the next coming days!

**Comment by alfg** [comment]
Hey @zachlevy, 

I just added a new endpoint to support this feature. https://github.com/alfg/murmur-rest/pull/27

Feel free to pull the latest and try it out!
```
curl -X POST \
  http://localhost:5000/servers/1/user/1/update \
  -F username=foobar2
```

**Comment by zachlevy** [comment]
Beautiful! works great, thanks!
