### ISSUE TITLE
Allow to configure the ICE communication with environment variables

### ISSUE THREAD

**Issue by koalp** [alfg/murmur-rest#32]
Currently, it is not possible to configure the ICE communication without modifying the `settings.py` file. This can be problematic when someone want to run the application from the docker image or from a package installation.

Therefore, I think that it would be nice to be able to configure the ICE host and port through environment variables.

**Comment by alfg** [comment]
Good idea. Besides the Ice host, what other settings do you think we should have configurable as an environment variable?

**Comment by koalp** [comment]
For the ICE, I only see the host and the port that could be configured.

Maybe other settings should also be available ? 
I'm not sure to understand what the `MURMUR_ROOT` is used for.

**Comment by alfg** [comment]
Yeah, the path of where the app is running from to find the relative ice file.
