### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by ACH1980** [alfg/murmur-rest#38]
I'm sure it's not an error with the program itself, but I'm doing something wrong. 

Here is what my directorys look like:

```ach1980@new:~/murmur-rest$ ls -la
total 104
drwxr-xr-x  5 ach1980 ach1980  4096 Apr  3 16:19 .
drwxr-xr-x 24 ach1980 ach1980  4096 Apr  3 14:38 ..
drwxr-xr-x  2 ach1980 ach1980  4096 Apr  3 16:19 app
-rw-r--r--  1 ach1980 ach1980   894 Apr  3 14:38 docker-compose.yml
-rw-r--r--  1 ach1980 ach1980  1076 Apr  3 14:38 Dockerfile
-rw-r--r--  1 ach1980 ach1980     8 Apr  3 14:38 .dockerignore
drwxr-xr-x  2 ach1980 ach1980  4096 Apr  3 14:38 etc
drwxr-xr-x  8 ach1980 ach1980  4096 Apr  3 14:38 .git
-rw-r--r--  1 ach1980 ach1980   357 Apr  3 14:38 .gitignore
-rwxr-xr-x  1 ach1980 ach1980 39939 Apr  3 14:38 Murmur.ice
-rw-r--r--  1 ach1980 ach1980  7620 Apr  3 14:38 README.md
-rw-r--r--  1 ach1980 ach1980   145 Apr  3 14:38 requirements.txt
-rw-r--r--  1 ach1980 ach1980   150 Apr  3 14:38 runserver.py
-rw-r--r--  1 ach1980 ach1980  1198 Apr  3 14:38 settings.py
-rw-r--r--  1 ach1980 ach1980  1376 Apr  3 16:19 settings.pyc
-rw-r--r--  1 ach1980 ach1980    86 Apr  3 14:38 wsgi.py
ach1980@new:~/murmur-rest$
```

And the murmur directory:
```ach1980@new:~/murmur$ ls -la
total 24
drwx------  2 ach1980       ach1980        4096 Apr  3 16:26 .
drwxr-xr-x 24 ach1980       ach1980        4096 Apr  3 14:38 ..
-rw-r--r--  1 ach1980       ach1980           0 Nov  2 23:50 .dbus.sh
-rw-r--r--  1 ach1980       ach1980       11116 Nov  2 23:55 murmur.ini
-rw-rw----  1 mumble-server mumble-server  1952 Nov  2 23:59 murmur.log
ach1980@new:~/murmur$
 ```

Can you tell me what to enter as `MURMUR_ROOT` and as `SLICE_FILE`?

I've tried the following for `MURMUR_ROOT`:
`/home/ach1980/murmur/` (which is `~/murmur/`)
`/home/ach1980/murmur-rest/` (which is `~/murmur-rest/`)

And the following for `SLICE_FILE`:
the absolute path (`/home/ach1980/murmur-rest/Murmur.ice`) with both of the above `MURMUR_ROOT`-Variations
and `Murmur.ice` with the latter `MURMUR_ROOT` (in the other it can't know in which folder it can find the File, I think)

**Comment by alfg** [comment]
As long as you're using the default path of Slice file, you shouldn't have to change the `MURMUR_ROOT` and `SLICE_FILE` settings. Can you print the full stack trace you are seeing?

**Comment by ACH1980** [comment]
Yeah of course, I guessed I had forgot something xD

```ach1980@new:~/murmur-rest$ python runserver.py 
Traceback (most recent call last):
  File "runserver.py", line 1, in <module>
    from app import app
  File "/home/ach1980/murmur-rest/app/__init__.py", line 30, in <module>
    Ice.loadSlice('', ['-I' + Ice.getSliceDir(), os.path.join(settings.MURMUR_ROOT, settings.SLICE_FILE)])
TypeError: cannot concatenate 'str' and 'NoneType' objects
ach1980@new:~/murmur-rest$ 
```

**Comment by alfg** [comment]
Hmm, yeah seems like either MURMUR_ROOT or SLICE_FILE is None. Using the defaults, what do both of those print out as?

**Comment by ACH1980** [comment]
For some reason no env variables are set. I'll set them again and try again and see what happens...

**Comment by alfg** [comment]
Also, please check if Ice is installed.
```
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Ice
>>> Ice.loadSlice
>>> Ice.getSliceDir()
'/usr/share/ice/slice'
>>>
```

**Comment by ACH1980** [comment]
Wait python 3? Seems like I've used 2 (I've followed the manual where no number is given, and when I just type `python` it says 2.7.16

**Comment by alfg** [comment]
Ah, yeah I'll update the readme with the Python version. I've upgraded the project to Python 3 last year.

**Comment by ACH1980** [comment]
Yeah, I'm testing with python3 and if it works I'll close the issue

**Comment by ACH1980** [comment]
Ok Ice seems to be not installed, how can I do this? In murmur itself it's succesfully active, but I guess I'll need a python module too, right?

**Comment by ACH1980** [comment]
Hmm I installed it with pip3 but it still says "No module named 'Ice'"

**Comment by alfg** [comment]
Right, if you're not using the Docker setup, then you can refer to the Dockerfile's Ice installation:
https://github.com/alfg/murmur-rest/blob/master/Dockerfile#L20-L22

You'll need `python3-zeroc-ice` and  `zeroc-ice-compilers`.

**Comment by ACH1980** [comment]
Ok, seems to work now. Thanks

**Comment by alfg** [comment]
> Hmm I installed it with pip3 but it still says "No module named 'Ice'"

Yeah, you'll have to use the Zeroc repositories. It won't be available in the standard pip repos.
