### ISSUE TITLE
error on master

### ISSUE THREAD

**Issue by handmeatowel** [alfg/murmur-rest#39]
I'm trying to get this running on a Debian machine with Python 3.9 installed, but I'm unable to get it running (I also have zero Python skills). I've read the README a couple of times; I don't think I've missed anything.

> #python3 runserver.py 
> Traceback (most recent call last):
>   File "/opt/murmur-rest/runserver.py", line 1, in <module>
>     from app import app
>   File "/opt/murmur-rest/app/__init__.py", line 30, in <module>
>     Ice.loadSlice('', ['-I' + Ice.getSliceDir(), os.path.join(settings.MURMUR_ROOT, settings.SLICE_FILE)])
> TypeError: can only concatenate str (not "NoneType") to str`

Any pointers would be much appreciated!

**Comment by alfg** [comment]
Hi @handmeatowel,

This seems similar to #38. Can you check if both `MURMUR_ROOT` and `SLICE_FILE` are set properly in `settings.py`? Also check if Ice is installed.

```
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Ice
>>> Ice.loadSlice
>>> Ice.getSliceDir()
'/usr/share/ice/slice'
>>>
```

**Comment by handmeatowel** [comment]
Thank you, alfg, for the really quick and helpful follow-up.
Indeed #38 helped; zeroc-ice-compilers had to be installed on Debian 11 and now "python3 runserver.py" seems to do what it should.

**Comment by alfg** [comment]
Good to hear. Glad you got it working!
