### ISSUE TITLE
Proxy API

### ISSUE THREAD

**Issue by BonnetAdam** [alfg/murmur-rest#40]
Hi, I have a mailserver on the same vps that the murmur-rest run, and I was needed to install a proxy on the vps, and now the API doesn't work. The proxy turn under NGINX, I did properly all the redirection. Do you have any idea how I can solve this problem

**Comment by alfg** [comment]
Hey @CrazyOutOff, do you have an example of the NGINX config? Are the required server and murmur ports open?

**Comment by BonnetAdam** [comment]
Hi, I was finnaly able to find a solution. I was using the wrong protocol. But thanks for the anwser.

**Comment by alfg** [comment]
Ah, good to know. Glad you figured out the issue.
