### ISSUE TITLE
communicator not destroyed during global destruction

### ISSUE THREAD

**Issue by BonnetAdam** [alfg/murmur-rest#41]
Hi so I came back with an other error, and that what I got when try to lunch wsgi.py but from not that long I also got that error from lunching the runserver.py. I try to add in the app/__init__.py a ice.detroy() to try to debug the situation but the bug is still there. Do you have any ideas on how I can resolve that problem ? 

Thanks in advance

**Comment by alfg** [comment]
Hi @CrazyOutOff, is there a stacktrace you can post demoing the bug?

**Comment by BonnetAdam** [comment]
<img width="670" alt="Screen Shot 2022-03-11 at 12 01 49 PM" src="https://user-images.githubusercontent.com/55563805/157854892-0859d82d-1e75-425b-a1b1-17635dc87d04.png">
I only have that when lunch python runserver.py

**Comment by BonnetAdam** [comment]
So, do you have any idea. To how I can fix this error ?

**Comment by alfg** [comment]
Are you running the ICE host locally? Are you using Docker or installed ice manually?

**Comment by BonnetAdam** [comment]
I just install one instance of mumble-server and turn on the API. The work before but since few days that doesn't...

**Comment by Vengelis** [comment]
This error appears if murmur is not linked with Ice. For this you have to go to the settings of murmur and activate the ice line

For debian:
- `nano /etc/mumbler-server.ini`
- go to line where ice settings is noted and uncomment line : `ice="tcp -h 127.0.0.1 -p 6502`
- save file
- restart mumbler-server
- enjoy :)

**Comment by alfg** [comment]
Thanks @Vengelis!
